  # Data Cleaning with Pandas #

Welcome to your introduction to Pandas and Jupyter Notebook!

Today we're going to learn how to read in a csv file, create a dataframe, identify different ways it may be dirty and learn some techniques for cleaning up our data set.

karrie.anne.kehoe@gmail.com/@karriekehoe

## Getting to grips with Jupyter Notebook and Pandas

Jupyter Notebook is an interactive, browser based programing environment. It can be used for multiple programming languages, for writing documentation and visualising data. If you want to learn more about what Jupyter Notebook can read its documentation at http://jupyter-notebook.readthedocs.io/en/latest/notebook.html

Pandas is a python library, designed for statistical analysis. It's very flexible, easy to use and has a range of useful built in functions. If you want to learn more about what Pandas can do, you can read its documentation at http://pandas.pydata.org/ or browse the cook book at http://pandas.pydata.org/pandas-docs/version/0.18.1/tutorials.html

### Shortcuts:
* `esc` - takes you into command mode
* `a` - insert cell above
* `b` - insert cell below
* `shift then tab` will show you the documentation for your code
* `shift and enter` will run your cell
* ` d d` will delete a cell

### Terminology ###

**Dataframe** - a dataframe is a two dimensional tabular data structure with labeled axes

**Series** - a series is similar to a list, array or a single column within a dataframe

## Starting off

First we need to import Pandas our python library to do so we use the line of code below. We use 'pd' as an alias to make it easier when typing in our code.
We are going to type 

`import pandas as pd`

In [1]:
import pandas as pd

Now we create a dataframe and read in our csv.

`df = pd.read_csv('filepath')`

In [3]:
df = pd.read_csv('/Users/karrie/Desktop/DATA_TRAINING/CIJ_2018/results.csv')

Let's look at the first ten rows of our data

`df.head(10)`

In [4]:
df.head(10)

,ECRef,RegulatedEntityName,RegulatedEntityType,Value,AcceptedDate,AccountingUnitName,DonorName,AccountingUnitsAsCentralParty,IsSponsorship,DonorStatus,...,IsReportedPrePoll,ReportingPeriodName,IsBequest,IsAggregation,RegulatedEntityId,AccountingUnitId,DonorId,CampaigningName,RegisterName,IsIrishSource
0,C0314887,Vote Leave Limited,Permitted Participant,"£40,000.00",17/06/2106,NaN,Anthony Clake,False,False,Individual,...,False,Referendum on the UK’s membership of the EU,False,False,3945,NaN,77235,NaN,NaN,False
1,C0363977,Plaid Cymru - The Party of Wales,Political Party,"£20,000.00",19/12/2018,Central Party,Mr Alun Ffred Jones,False,False,Individual,...,NaN,Q4 2017,False,True,77,NaN,83318,NaN,Great Britain,False
2,C0395370,Conservative Middle East Council,Regulated Donee,"£50,000.00",06/06/2018,NaN,Rosemary Said,False,False,Individual,...,NaN,May-18,False,False,1390,NaN,68108,NaN,Great Britain,False
3,V0395331,Bob Stewart MP,Regulated Donee,"£2,792.00",29/05/2018,NaN,Government of Kazakhstan,False,False,Other,...,NaN,May-18,False,False,4012,NaN,76273,NaN,Great Britain,False
4,C0395341,Stephen Kinnock MP,Regulated Donee,"£7,000.00",17/05/2018,NaN,Community Union,False,False,Trade Union,...,NaN,May-18,False,False,4158,NaN,74244,NaN,Great Britain,False
5,C0395372,The Spring Lunch,Regulated Donee,"£9,000.00",16/05/2018,NaN,Sun Mark Ltd,False,False,Company,...,NaN,May-18,False,False,1621,NaN,84371,NaN,Great Britain,False
6,C0395371,Your Liberal Britain,Regulated Donee,"£10,000.00",16/05/2018,NaN,Mark Petterson,False,False,Individual,...,NaN,May-18,False,False,6603,NaN,84370,NaN,Great Britain,False
7,C0395373,The Spring Lunch,Regulated Donee,"£8,000.00",16/05/2018,NaN,Lorraine Spencer,False,False,Individual,...,NaN,May-18,False,False,1621,NaN,84372,NaN,Great Britain,False
8,C0395342,Tom Watson MP,Regulated Donee,"£3,000.00",14/05/2018,NaN,No 1 Skip Hire,False,False,Company,...,NaN,May-18,False,False,1846,NaN,84344,NaN,Great Britain,False
9,C0395333,Conservative Middle East Council,Regulated Donee,"£12,500.00",10/05/2018,NaN,Mark Hilton,False,False,Individual,...,NaN,May-18,False,False,1390,NaN,77412,NaN,Great Britain,False

Next we need to know what data types we're dealing with for each column in our dataframe

`df.dtypes`

In [5]:
df.dtypes

ECRef                             object
RegulatedEntityName               object
RegulatedEntityType               object
Value                             object
AcceptedDate                      object
AccountingUnitName                object
DonorName                         object
AccountingUnitsAsCentralParty       bool
IsSponsorship                       bool
DonorStatus                       object
RegulatedDoneeType                object
CompanyRegistrationNumber         object
Postcode                          object
DonationType                      object
NatureOfDonation                  object
PurposeOfVisit                    object
DonationAction                   float64
ReceivedDate                      object
ReportedDate                      object
IsReportedPrePoll                 object
ReportingPeriodName               object
IsBequest                           bool
IsAggregation                       bool
RegulatedEntityId                  int64
AccountingUnitId                 float64
DonorId                            int64
CampaigningName                   object
RegisterName                      object
IsIrishSource                     object
dtype: object

We use .shape to find the dimensions of our data

`df.shape`

In [6]:
df.shape

(18480, 29)

## Data Problems: 
* Dates are python objects and not a datetime object
* Values are python objects and not ints or floats, so we can't perform any calculations on them
* We need a year column, perhaps even a month column
* There may be leading or strail spaces in our data

Before we change anything we're going to create a copy of our dataframe and clean that up

`df2.copy()`

In [7]:
df2 = df.copy()

## Cleaning strings

We need to clean up the value column and convert it to an integer so we can count it. How do we check that it's worked?

`df2['col'] = df2['col'].str.replace('£', '')`

In [8]:
df2['Value_clean'] = df2['Value'].str.replace('£', '')

In [9]:
df2.head()

,ECRef,RegulatedEntityName,RegulatedEntityType,Value,AcceptedDate,AccountingUnitName,DonorName,AccountingUnitsAsCentralParty,IsSponsorship,DonorStatus,...,ReportingPeriodName,IsBequest,IsAggregation,RegulatedEntityId,AccountingUnitId,DonorId,CampaigningName,RegisterName,IsIrishSource,Value_clean
0,C0314887,Vote Leave Limited,Permitted Participant,"£40,000.00",17/06/2106,NaN,Anthony Clake,False,False,Individual,...,Referendum on the UK’s membership of the EU,False,False,3945,NaN,77235,NaN,NaN,False,"40,000.00"
1,C0363977,Plaid Cymru - The Party of Wales,Political Party,"£20,000.00",19/12/2018,Central Party,Mr Alun Ffred Jones,False,False,Individual,...,Q4 2017,False,True,77,NaN,83318,NaN,Great Britain,False,"20,000.00"
2,C0395370,Conservative Middle East Council,Regulated Donee,"£50,000.00",06/06/2018,NaN,Rosemary Said,False,False,Individual,...,May-18,False,False,1390,NaN,68108,NaN,Great Britain,False,"50,000.00"
3,V0395331,Bob Stewart MP,Regulated Donee,"£2,792.00",29/05/2018,NaN,Government of Kazakhstan,False,False,Other,...,May-18,False,False,4012,NaN,76273,NaN,Great Britain,False,"2,792.00"
4,C0395341,Stephen Kinnock MP,Regulated Donee,"£7,000.00",17/05/2018,NaN,Community Union,False,False,Trade Union,...,May-18,False,False,4158,NaN,74244,NaN,Great Britain,False,"7,000.00"

In [10]:
df2['Value_clean'] = df2['Value_clean'].str.replace(',', '')
df2['Value_clean'] = df2['Value_clean'].str.replace('.', '')

In [11]:
df2.head()

,ECRef,RegulatedEntityName,RegulatedEntityType,Value,AcceptedDate,AccountingUnitName,DonorName,AccountingUnitsAsCentralParty,IsSponsorship,DonorStatus,...,ReportingPeriodName,IsBequest,IsAggregation,RegulatedEntityId,AccountingUnitId,DonorId,CampaigningName,RegisterName,IsIrishSource,Value_clean
0,C0314887,Vote Leave Limited,Permitted Participant,"£40,000.00",17/06/2106,NaN,Anthony Clake,False,False,Individual,...,Referendum on the UK’s membership of the EU,False,False,3945,NaN,77235,NaN,NaN,False,4000000
1,C0363977,Plaid Cymru - The Party of Wales,Political Party,"£20,000.00",19/12/2018,Central Party,Mr Alun Ffred Jones,False,False,Individual,...,Q4 2017,False,True,77,NaN,83318,NaN,Great Britain,False,2000000
2,C0395370,Conservative Middle East Council,Regulated Donee,"£50,000.00",06/06/2018,NaN,Rosemary Said,False,False,Individual,...,May-18,False,False,1390,NaN,68108,NaN,Great Britain,False,5000000
3,V0395331,Bob Stewart MP,Regulated Donee,"£2,792.00",29/05/2018,NaN,Government of Kazakhstan,False,False,Other,...,May-18,False,False,4012,NaN,76273,NaN,Great Britain,False,279200
4,C0395341,Stephen Kinnock MP,Regulated Donee,"£7,000.00",17/05/2018,NaN,Community Union,False,False,Trade Union,...,May-18,False,False,4158,NaN,74244,NaN,Great Britain,False,700000

Now check to see if that worked

In [12]:
df2.dtypes

ECRef                             object
RegulatedEntityName               object
RegulatedEntityType               object
Value                             object
AcceptedDate                      object
AccountingUnitName                object
DonorName                         object
AccountingUnitsAsCentralParty       bool
IsSponsorship                       bool
DonorStatus                       object
RegulatedDoneeType                object
CompanyRegistrationNumber         object
Postcode                          object
DonationType                      object
NatureOfDonation                  object
PurposeOfVisit                    object
DonationAction                   float64
ReceivedDate                      object
ReportedDate                      object
IsReportedPrePoll                 object
ReportingPeriodName               object
IsBequest                           bool
IsAggregation                       bool
RegulatedEntityId                  int64
AccountingUnitId                 float64
DonorId                            int64
CampaigningName                   object
RegisterName                      object
IsIrishSource                     object
Value_clean                       object
dtype: object

## Changing data types

Ok, no luck. We need to explicitly change the data type for the new Value clean column.

`df2['Value_clean'] = pd.to_numeric(df2['Value_clean'])`

In [13]:
df2['Value_clean'] = pd.to_numeric(df2['Value_clean'])
df2.dtypes

ECRef                             object
RegulatedEntityName               object
RegulatedEntityType               object
Value                             object
AcceptedDate                      object
AccountingUnitName                object
DonorName                         object
AccountingUnitsAsCentralParty       bool
IsSponsorship                       bool
DonorStatus                       object
RegulatedDoneeType                object
CompanyRegistrationNumber         object
Postcode                          object
DonationType                      object
NatureOfDonation                  object
PurposeOfVisit                    object
DonationAction                   float64
ReceivedDate                      object
ReportedDate                      object
IsReportedPrePoll                 object
ReportingPeriodName               object
IsBequest                           bool
IsAggregation                       bool
RegulatedEntityId                  int64
AccountingUnitId                 float64
DonorId                            int64
CampaigningName                   object
RegisterName                      object
IsIrishSource                     object
Value_clean                        int64
dtype: object

However we need to make sure that we count our donations amount correctly. So let's divide the column by 100.

In [14]:
df2['Value_clean'] = df2['Value_clean']/100
df2.head()

,ECRef,RegulatedEntityName,RegulatedEntityType,Value,AcceptedDate,AccountingUnitName,DonorName,AccountingUnitsAsCentralParty,IsSponsorship,DonorStatus,...,ReportingPeriodName,IsBequest,IsAggregation,RegulatedEntityId,AccountingUnitId,DonorId,CampaigningName,RegisterName,IsIrishSource,Value_clean
0,C0314887,Vote Leave Limited,Permitted Participant,"£40,000.00",17/06/2106,NaN,Anthony Clake,False,False,Individual,...,Referendum on the UK’s membership of the EU,False,False,3945,NaN,77235,NaN,NaN,False,40000.0
1,C0363977,Plaid Cymru - The Party of Wales,Political Party,"£20,000.00",19/12/2018,Central Party,Mr Alun Ffred Jones,False,False,Individual,...,Q4 2017,False,True,77,NaN,83318,NaN,Great Britain,False,20000.0
2,C0395370,Conservative Middle East Council,Regulated Donee,"£50,000.00",06/06/2018,NaN,Rosemary Said,False,False,Individual,...,May-18,False,False,1390,NaN,68108,NaN,Great Britain,False,50000.0
3,V0395331,Bob Stewart MP,Regulated Donee,"£2,792.00",29/05/2018,NaN,Government of Kazakhstan,False,False,Other,...,May-18,False,False,4012,NaN,76273,NaN,Great Britain,False,2792.0
4,C0395341,Stephen Kinnock MP,Regulated Donee,"£7,000.00",17/05/2018,NaN,Community Union,False,False,Trade Union,...,May-18,False,False,4158,NaN,74244,NaN,Great Britain,False,7000.0

## Dropping and re-naming columns

Let's clean up our dataframe a bit by dropping the original Value column - the 1 is the index, so we're saying it's the column with the value Value in the first row 

`df2 = df2.drop('Value', 1)`

In [15]:
df2 = df2.drop('Value', 1)
df2.head()

,ECRef,RegulatedEntityName,RegulatedEntityType,AcceptedDate,AccountingUnitName,DonorName,AccountingUnitsAsCentralParty,IsSponsorship,DonorStatus,RegulatedDoneeType,...,ReportingPeriodName,IsBequest,IsAggregation,RegulatedEntityId,AccountingUnitId,DonorId,CampaigningName,RegisterName,IsIrishSource,Value_clean
0,C0314887,Vote Leave Limited,Permitted Participant,17/06/2106,NaN,Anthony Clake,False,False,Individual,NaN,...,Referendum on the UK’s membership of the EU,False,False,3945,NaN,77235,NaN,NaN,False,40000.0
1,C0363977,Plaid Cymru - The Party of Wales,Political Party,19/12/2018,Central Party,Mr Alun Ffred Jones,False,False,Individual,NaN,...,Q4 2017,False,True,77,NaN,83318,NaN,Great Britain,False,20000.0
2,C0395370,Conservative Middle East Council,Regulated Donee,06/06/2018,NaN,Rosemary Said,False,False,Individual,Members Association,...,May-18,False,False,1390,NaN,68108,NaN,Great Britain,False,50000.0
3,V0395331,Bob Stewart MP,Regulated Donee,29/05/2018,NaN,Government of Kazakhstan,False,False,Other,MP - Member of Parliament,...,May-18,False,False,4012,NaN,76273,NaN,Great Britain,False,2792.0
4,C0395341,Stephen Kinnock MP,Regulated Donee,17/05/2018,NaN,Community Union,False,False,Trade Union,MP - Member of Parliament,...,May-18,False,False,4158,NaN,74244,NaN,Great Britain,False,7000.0

Now that's gone, let's rename the Value clean column

`df2 = df2.rename(columns={'old_name': 'new_name'})`

In [16]:
df2 = df2.rename(columns={'Value_clean': 'Value'})
df2.head()

,ECRef,RegulatedEntityName,RegulatedEntityType,AcceptedDate,AccountingUnitName,DonorName,AccountingUnitsAsCentralParty,IsSponsorship,DonorStatus,RegulatedDoneeType,...,ReportingPeriodName,IsBequest,IsAggregation,RegulatedEntityId,AccountingUnitId,DonorId,CampaigningName,RegisterName,IsIrishSource,Value
0,C0314887,Vote Leave Limited,Permitted Participant,17/06/2106,NaN,Anthony Clake,False,False,Individual,NaN,...,Referendum on the UK’s membership of the EU,False,False,3945,NaN,77235,NaN,NaN,False,40000.0
1,C0363977,Plaid Cymru - The Party of Wales,Political Party,19/12/2018,Central Party,Mr Alun Ffred Jones,False,False,Individual,NaN,...,Q4 2017,False,True,77,NaN,83318,NaN,Great Britain,False,20000.0
2,C0395370,Conservative Middle East Council,Regulated Donee,06/06/2018,NaN,Rosemary Said,False,False,Individual,Members Association,...,May-18,False,False,1390,NaN,68108,NaN,Great Britain,False,50000.0
3,V0395331,Bob Stewart MP,Regulated Donee,29/05/2018,NaN,Government of Kazakhstan,False,False,Other,MP - Member of Parliament,...,May-18,False,False,4012,NaN,76273,NaN,Great Britain,False,2792.0
4,C0395341,Stephen Kinnock MP,Regulated Donee,17/05/2018,NaN,Community Union,False,False,Trade Union,MP - Member of Parliament,...,May-18,False,False,4158,NaN,74244,NaN,Great Britain,False,7000.0

Let's make sure there aren't any trail or leading spaces in the column names, if so this could cause havoc

`df2.columns`

In [17]:
df2.columns

Index(['ECRef', 'RegulatedEntityName', 'RegulatedEntityType', 'AcceptedDate',
       'AccountingUnitName', 'DonorName', 'AccountingUnitsAsCentralParty',
       'IsSponsorship', 'DonorStatus', 'RegulatedDoneeType',
       'CompanyRegistrationNumber', 'Postcode', 'DonationType',
       'NatureOfDonation', 'PurposeOfVisit', 'DonationAction', 'ReceivedDate',
       'ReportedDate', 'IsReportedPrePoll', 'ReportingPeriodName', 'IsBequest',
       'IsAggregation', 'RegulatedEntityId', 'AccountingUnitId', 'DonorId',
       'CampaigningName', 'RegisterName', 'IsIrishSource', 'Value'],
      dtype='object')

All good, but maybe there are some in the donor names.

`df2['column'].unique()`

In [18]:
df2['DonorName'].unique()

array([' Anthony Clake', 'Mr Alun Ffred Jones', ' Rosemary Said', ...,
       'Mr Alex Sobel', 'Mr Mohammed Miah', 'Mr H E Huppert'], dtype=object)

Yup just like I thought, there is a leading space in Anthony Clarke, we need to fix that. First though we need to make sure that the DonorName is a column of strings, if there are any numeric names in there it'll confuse python and we won't be able to manipulate the column

`df2['column'] = df2['column'].astype(str)`

In [19]:
df2['DonorName'] = df2['DonorName'].astype(str)

Ok now we're going to strip out any of those trail spaces

`df2['column']=df2['column'].map(str.strip)`

In [20]:
df2['DonorName_clean']=df2['DonorName'].map(str.strip)

Did that work?

`df2[column].unique()`

In [21]:
df2['DonorName_clean'].unique()

array(['Anthony Clake', 'Mr Alun Ffred Jones', 'Rosemary Said', ...,
       'Mr Alex Sobel', 'Mr Mohammed Miah', 'Mr H E Huppert'], dtype=object)

## Dates and Years

Ok, the reporting periods are pretty messy, so let's create a new column with the year value in there. We can extract that from one of the date columns. To do that we need to import the new library called datetime

`import datetime`

In [22]:
import datetime

Now we're going to strip the year from the accepted date and insert the value in a new column called 'Year'

`df2['YEAR'] = pd.DatetimeIndex(df2['AcceptedDate']).year`

In [23]:
df2['YEAR'] = pd.DatetimeIndex(df2['AcceptedDate']).year

Did that work? If so let's try do the same for the month value, same formula as year

In [24]:
df2.head()

,ECRef,RegulatedEntityName,RegulatedEntityType,AcceptedDate,AccountingUnitName,DonorName,AccountingUnitsAsCentralParty,IsSponsorship,DonorStatus,RegulatedDoneeType,...,IsAggregation,RegulatedEntityId,AccountingUnitId,DonorId,CampaigningName,RegisterName,IsIrishSource,Value,DonorName_clean,YEAR
0,C0314887,Vote Leave Limited,Permitted Participant,17/06/2106,NaN,Anthony Clake,False,False,Individual,NaN,...,False,3945,NaN,77235,NaN,NaN,False,40000.0,Anthony Clake,2106
1,C0363977,Plaid Cymru - The Party of Wales,Political Party,19/12/2018,Central Party,Mr Alun Ffred Jones,False,False,Individual,NaN,...,True,77,NaN,83318,NaN,Great Britain,False,20000.0,Mr Alun Ffred Jones,2018
2,C0395370,Conservative Middle East Council,Regulated Donee,06/06/2018,NaN,Rosemary Said,False,False,Individual,Members Association,...,False,1390,NaN,68108,NaN,Great Britain,False,50000.0,Rosemary Said,2018
3,V0395331,Bob Stewart MP,Regulated Donee,29/05/2018,NaN,Government of Kazakhstan,False,False,Other,MP - Member of Parliament,...,False,4012,NaN,76273,NaN,Great Britain,False,2792.0,Government of Kazakhstan,2018
4,C0395341,Stephen Kinnock MP,Regulated Donee,17/05/2018,NaN,Community Union,False,False,Trade Union,MP - Member of Parliament,...,False,4158,NaN,74244,NaN,Great Britain,False,7000.0,Community Union,2018

In [26]:
df2['MONTH'] = pd.DatetimeIndex(df2['AcceptedDate']).month

In [27]:
df2.head()

,ECRef,RegulatedEntityName,RegulatedEntityType,AcceptedDate,AccountingUnitName,DonorName,AccountingUnitsAsCentralParty,IsSponsorship,DonorStatus,RegulatedDoneeType,...,RegulatedEntityId,AccountingUnitId,DonorId,CampaigningName,RegisterName,IsIrishSource,Value,DonorName_clean,YEAR,MONTH
0,C0314887,Vote Leave Limited,Permitted Participant,17/06/2106,NaN,Anthony Clake,False,False,Individual,NaN,...,3945,NaN,77235,NaN,NaN,False,40000.0,Anthony Clake,2106,6
1,C0363977,Plaid Cymru - The Party of Wales,Political Party,19/12/2018,Central Party,Mr Alun Ffred Jones,False,False,Individual,NaN,...,77,NaN,83318,NaN,Great Britain,False,20000.0,Mr Alun Ffred Jones,2018,12
2,C0395370,Conservative Middle East Council,Regulated Donee,06/06/2018,NaN,Rosemary Said,False,False,Individual,Members Association,...,1390,NaN,68108,NaN,Great Britain,False,50000.0,Rosemary Said,2018,6
3,V0395331,Bob Stewart MP,Regulated Donee,29/05/2018,NaN,Government of Kazakhstan,False,False,Other,MP - Member of Parliament,...,4012,NaN,76273,NaN,Great Britain,False,2792.0,Government of Kazakhstan,2018,5
4,C0395341,Stephen Kinnock MP,Regulated Donee,17/05/2018,NaN,Community Union,False,False,Trade Union,MP - Member of Parliament,...,4158,NaN,74244,NaN,Great Britain,False,7000.0,Community Union,2018,5

## Shrinking dataframes

Ok finally let's get rid of some of the columns and make our dataframe a more manageable size

To do this we need a list of column names again

In [28]:
df2.columns

Index(['ECRef', 'RegulatedEntityName', 'RegulatedEntityType', 'AcceptedDate',
       'AccountingUnitName', 'DonorName', 'AccountingUnitsAsCentralParty',
       'IsSponsorship', 'DonorStatus', 'RegulatedDoneeType',
       'CompanyRegistrationNumber', 'Postcode', 'DonationType',
       'NatureOfDonation', 'PurposeOfVisit', 'DonationAction', 'ReceivedDate',
       'ReportedDate', 'IsReportedPrePoll', 'ReportingPeriodName', 'IsBequest',
       'IsAggregation', 'RegulatedEntityId', 'AccountingUnitId', 'DonorId',
       'CampaigningName', 'RegisterName', 'IsIrishSource', 'Value',
       'DonorName_clean', 'YEAR', 'MONTH'],
      dtype='object')

Alright let's figure what we need and shrink the dataframe

`df2 = df2[['RegulatedEntityName', 'AcceptedDate', 'DonorName_clean', 'DonorStatus', 'YEAR', 'Value', 'RegulatedEntityType', 'DonorId', 'CampaigningName']]`

In [29]:
df2 = df2[['RegulatedEntityName', 'AcceptedDate', 'DonorName_clean', 'DonorStatus', 'YEAR', 'Value', 'RegulatedEntityType', 'DonorId', 'CampaigningName']]

In [30]:
df2.head()

,RegulatedEntityName,AcceptedDate,DonorName_clean,DonorStatus,YEAR,Value,RegulatedEntityType,DonorId,CampaigningName
0,Vote Leave Limited,17/06/2106,Anthony Clake,Individual,2106,40000.0,Permitted Participant,77235,NaN
1,Plaid Cymru - The Party of Wales,19/12/2018,Mr Alun Ffred Jones,Individual,2018,20000.0,Political Party,83318,NaN
2,Conservative Middle East Council,06/06/2018,Rosemary Said,Individual,2018,50000.0,Regulated Donee,68108,NaN
3,Bob Stewart MP,29/05/2018,Government of Kazakhstan,Other,2018,2792.0,Regulated Donee,76273,NaN
4,Stephen Kinnock MP,17/05/2018,Community Union,Trade Union,2018,7000.0,Regulated Donee,74244,NaN

## Saving our data

Ok finally let's save our clean for the next class

`df2.to_csv('clean_data.csv', encoding='utf8')`

In [31]:
df2.to_csv('clean_data.csv', encoding='utf8')